# Generated by Django 4.2.3 on 2023-07-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.TextField(max_length=50)),
                ('device', models.TextField()),
                ('primer_nombre', models.TextField()),
                ('segundo_nombre', models.TextField(blank=True, default='')),
                ('apellido_paterno', models.TextField()),
                ('apellido_materno', models.TextField()),
                ('numero_contacto', models.IntegerField(blank=True, default=0)),
                ('notas', models.TextField(blank=True, default='')),
                ('fecha_evento', models.TextField()),
            ],
        ),
    ]
